os: Ubuntu2004
platform:
  - x64
install:
  - sudo apt update && sudo apt install --allow-unauthenticated -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils ruby-dev libvirt-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
  - sudo dpkg -i vagrant_2.2.14_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule update --init --recursive
build_script:
  - cp -v salt/roots/pillar/nginx.sls.example salt/roots/pillar/nginx.sls
  - cp -v salt/roots/pillar/grafana.sls.example salt/roots/pillar/grafana.sls
  - cp -v salt/roots/formulas/nginx-formula/nginx/files/https.conf.example salt/roots/formulas/nginx-formula/nginx/files/https.conf
  - cp -v vagrant/examples/Vagrantfile.grafana-box.fedora-34.x86_64.example vagrant/Vagrantfile.grafana-box
  - sudo vagrant up --provider=libvirt grafana-box
  - sudo vagrant ssh grafana-box -- sudo salt-call state.highstate
  - sudo vagrant ssh grafana-box -- sudo salt-call state.sls grafana
  - sudo vagrant ssh grafana-box -- sudo salt-call state.sls grafana.config.nginx
  - sudo vagrant ssh grafana-box -- sudo salt-call state.sls nginx.service
  - sudo vagrant destroy --force grafana-box
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
